<?php

namespace App\Config;

use CodeIgniter\Config\BaseConfig;

class DtePaises extends BaseConfig
{
    // CAT-001 Ambiente de destino	
    public $paises = [

        'AF' => 'Afganistán',
        'AX' => 'Aland',
        'AL' => 'Albania',
        'DE' => 'Alemania',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguila',
        'AQ' => 'Antártica',
        'AG' => 'Antigua y Barbuda',
        'AW' => 'Aruba',
        'SA' => 'Arabia Saudita',
        'DZ' => 'Argelia',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaiyán',
        'BS' => 'Bahamas',
        'BH' => 'Bahrein',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BE' => 'Bélgica',
        'BZ' => 'Belice',
        'BJ' => 'Benin',
        'BM' => 'Bermudas',
        'BY' => 'Bielorrusia',
        'BO' => 'Bolivia',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'BA' => 'Bosnia-Herzegovina',
        'BW' => 'Botswana',
        'BR' => 'Brasil',
        'BN' => 'Brunei',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'BT' => 'Bután',
        'SV' => 'El Salvador',
        'US' => 'Estados Unidos',
        'GT' => 'Guatemala',
        'HN' => 'Honduras',
        'NI' => 'Nicaragua',
        'CR' => 'Costa Rica',
        'PA' => 'Panamá',
        'MX' => 'México',
        'ES' => 'España',
        'FR' => 'Francia',
        'IT' => 'Italia',
        'CN' => 'China',
        'JP' => 'Japón',
        'KR' => 'República de Corea',
        'CO' => 'Colombia',
        'PE' => 'Perú',
        'CL' => 'Chile',
        'VE' => 'Venezuela',
        'UY' => 'Uruguay',
        'PY' => 'Paraguay',
        'CA' => 'Canadá',
        'GB' => 'Reino Unido',
        'ZA' => 'Sudáfrica',
        'EG' => 'Egipto',
        'MA' => 'Marruecos',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'RU' => 'Rusia',
        'UA' => 'Ucrania',
        'TR' => 'Turquía',
        'AE' => 'Emiratos Árabes Unidos',
        'NZ' => 'Nueva Zelanda',
        'CU' => 'Cuba',
        'DO' => 'República Dominicana',
        'JM' => 'Jamaica',
        'PH' => 'Filipinas',
        'TH' => 'Tailandia',
        'VN' => 'Vietnam',
        'QA' => 'Qatar',
        'SG' => 'Singapur',
        'IL' => 'Israel',
        'CH' => 'Suiza',
        'SE' => 'Suecia',
        'NO' => 'Noruega',
        'FI' => 'Finlandia',
        'DK' => 'Dinamarca',
        'IE' => 'Irlanda',
        'PT' => 'Portugal',
        'NL' => 'Países Bajos',
        'PL' => 'Polonia',
        'CZ' => 'República Checa',
        'HU' => 'Hungría',
        'RO' => 'Rumania',
        'SK' => 'Eslovaquia',
        'SI' => 'Eslovenia',
        'HR' => 'Croacia',
        'RS' => 'Serbia',
        'ME' => 'Montenegro',
        'MK' => 'Macedonia',

    ];
}
