<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['id' => 1, 'nombre' => 'Atiquizaya', 'departamento_id' => 1],
            ['id' => 2, 'nombre' => 'El Refugio', 'departamento_id' => 1],
            ['id' => 3, 'nombre' => 'San Lorenzo', 'departamento_id' => 1],
            ['id' => 4, 'nombre' => 'Turín', 'departamento_id' => 1],
            ['id' => 5, 'nombre' => 'Ahuachapán', 'departamento_id' => 1],
            ['id' => 6, 'nombre' => 'Apaneca', 'departamento_id' => 1],
            ['id' => 7, 'nombre' => 'Concepción de Ataco', 'departamento_id' => 1],
            ['id' => 8, 'nombre' => 'Tacuba', 'departamento_id' => 1],
            ['id' => 9, 'nombre' => 'Guaymango', 'departamento_id' => 1],
            ['id' => 10, 'nombre' => 'Jujutla', 'departamento_id' => 1],
            ['id' => 11, 'nombre' => 'San Francisco Menéndez', 'departamento_id' => 1],
            ['id' => 12, 'nombre' => 'San Pedro Puxtla', 'departamento_id' => 1],
            ['id' => 13, 'nombre' => 'Cinquera', 'departamento_id' => 2],
            ['id' => 14, 'nombre' => 'Ilobasco', 'departamento_id' => 2],
            ['id' => 15, 'nombre' => 'Jutiapa', 'departamento_id' => 2],
            ['id' => 16, 'nombre' => 'Tejutepeque', 'departamento_id' => 2],
            ['id' => 17, 'nombre' => 'Guacotecti', 'departamento_id' => 2],
            ['id' => 18, 'nombre' => 'San Isidro', 'departamento_id' => 2],
            ['id' => 19, 'nombre' => 'Sensuntepeque', 'departamento_id' => 2],
            ['id' => 20, 'nombre' => 'Victoria', 'departamento_id' => 2],
            ['id' => 21, 'nombre' => 'Agua Caliente', 'departamento_id' => 3],
            ['id' => 22, 'nombre' => 'Arcatao', 'departamento_id' => 3],
            ['id' => 23, 'nombre' => 'Azacualpa', 'departamento_id' => 3],
            ['id' => 24, 'nombre' => 'Cancasque', 'departamento_id' => 3],
            ['id' => 25, 'nombre' => 'Chalatenango', 'departamento_id' => 3],
            ['id' => 26, 'nombre' => 'Citalá', 'departamento_id' => 3],
            ['id' => 27, 'nombre' => 'Comalapa', 'departamento_id' => 3],
            ['id' => 28, 'nombre' => 'Concepción Quezaltepeque', 'departamento_id' => 3],
            ['id' => 29, 'nombre' => 'Dulce Nombre de María', 'departamento_id' => 3],
            ['id' => 30, 'nombre' => 'El Carrizal', 'departamento_id' => 3],
            ['id' => 31, 'nombre' => 'El Paraíso', 'departamento_id' => 3],
            ['id' => 32, 'nombre' => 'La Laguna', 'departamento_id' => 3],
            ['id' => 33, 'nombre' => 'La Palma', 'departamento_id' => 3],
            ['id' => 34, 'nombre' => 'La Reina', 'departamento_id' => 3],
            ['id' => 35, 'nombre' => 'Las Flores', 'departamento_id' => 3],
            ['id' => 36, 'nombre' => 'Las Vueltas', 'departamento_id' => 3],
            ['id' => 37, 'nombre' => 'Nombre de Jesús', 'departamento_id' => 3],
            ['id' => 38, 'nombre' => 'Nueva Concepción', 'departamento_id' => 3],
            ['id' => 39, 'nombre' => 'Nueva Trinidad', 'departamento_id' => 3],
            ['id' => 40, 'nombre' => 'Ojos de Agua', 'departamento_id' => 3],
            ['id' => 41, 'nombre' => 'Potonico', 'departamento_id' => 3],
            ['id' => 42, 'nombre' => 'San Antonio de la Cruz', 'departamento_id' => 3],
            ['id' => 43, 'nombre' => 'San Antonio Los Ranchos', 'departamento_id' => 3],
            ['id' => 44, 'nombre' => 'San Fernando', 'departamento_id' => 3],
            ['id' => 45, 'nombre' => 'San Francisco Lempa', 'departamento_id' => 3],
            ['id' => 46, 'nombre' => 'San Francisco Morazán', 'departamento_id' => 3],
            ['id' => 47, 'nombre' => 'San Ignacio', 'departamento_id' => 3],
            ['id' => 48, 'nombre' => 'San Isidro Labrador', 'departamento_id' => 3],
            ['id' => 49, 'nombre' => 'San Luis del Carmen', 'departamento_id' => 3],
            ['id' => 50, 'nombre' => 'San Miguel de Mercedes', 'departamento_id' => 3],
            ['id' => 51, 'nombre' => 'San Rafael', 'departamento_id' => 3],
            ['id' => 52, 'nombre' => 'Santa Rita', 'departamento_id' => 3],
            ['id' => 53, 'nombre' => 'Tejutla', 'departamento_id' => 3],
            ['id' => 54, 'nombre' => 'Suchitoto', 'departamento_id' => 4],
            ['id' => 55, 'nombre' => 'San José Guayabal', 'departamento_id' => 4],
            ['id' => 56, 'nombre' => 'Oratorio de Concepción', 'departamento_id' => 4],
            ['id' => 57, 'nombre' => 'San Bartolomé Perulapía', 'departamento_id' => 4],
            ['id' => 58, 'nombre' => 'San Pedro Perulapán', 'departamento_id' => 4],
            ['id' => 59, 'nombre' => 'Cojutepeque (capital)', 'departamento_id' => 4],
            ['id' => 60, 'nombre' => 'Candelaria', 'departamento_id' => 4],
            ['id' => 61, 'nombre' => 'El Carmen', 'departamento_id' => 4],
            ['id' => 62, 'nombre' => 'El Rosario', 'departamento_id' => 4],
            ['id' => 63, 'nombre' => 'Monte San Juan', 'departamento_id' => 4],
            ['id' => 64, 'nombre' => 'San Cristóbal', 'departamento_id' => 4],
            ['id' => 65, 'nombre' => 'San Rafael Cedros', 'departamento_id' => 4],
            ['id' => 66, 'nombre' => 'San Ramón', 'departamento_id' => 4],
            ['id' => 67, 'nombre' => 'Santa Cruz Analquito', 'departamento_id' => 4],
            ['id' => 68, 'nombre' => 'Santa Cruz Michapa', 'departamento_id' => 4],
            ['id' => 69, 'nombre' => 'Tenancingo', 'departamento_id' => 4],
            ['id' => 70, 'nombre' => 'Santa Tecla', 'departamento_id' => 5],
            ['id' => 71, 'nombre' => 'Colón', 'departamento_id' => 5],
            ['id' => 72, 'nombre' => 'San Juan Opico', 'departamento_id' => 5],
            ['id' => 73, 'nombre' => 'Ciudad Arce', 'departamento_id' => 5],
            ['id' => 74, 'nombre' => 'Quezaltepeque', 'departamento_id' => 5],
            ['id' => 75, 'nombre' => 'La Libertad', 'departamento_id' => 5],
            ['id' => 76, 'nombre' => 'Antiguo Cuscatlán', 'departamento_id' => 5],
            ['id' => 77, 'nombre' => 'Zaragoza', 'departamento_id' => 5],
            ['id' => 78, 'nombre' => 'San Pablo Tacachico', 'departamento_id' => 5],
            ['id' => 79, 'nombre' => 'Huizúcar', 'departamento_id' => 5],
            ['id' => 80, 'nombre' => 'Tepecoyo', 'departamento_id' => 5],
            ['id' => 81, 'nombre' => 'San José Villanueva', 'departamento_id' => 5],
            ['id' => 82, 'nombre' => 'Tamanique', 'departamento_id' => 5],
            ['id' => 83, 'nombre' => 'Teotepeque', 'departamento_id' => 5],
            ['id' => 84, 'nombre' => 'Sacacoyo', 'departamento_id' => 5],
            ['id' => 85, 'nombre' => 'Comasagua', 'departamento_id' => 5],
            ['id' => 86, 'nombre' => 'Jayaque', 'departamento_id' => 5],
            ['id' => 87, 'nombre' => 'Chiltiupán', 'departamento_id' => 5],
            ['id' => 88, 'nombre' => 'Talnique', 'departamento_id' => 5],
            ['id' => 89, 'nombre' => 'San Matías', 'departamento_id' => 5],
            ['id' => 90, 'nombre' => 'Nuevo Cuscatlán', 'departamento_id' => 5],
            ['id' => 91, 'nombre' => 'Jicalapa', 'departamento_id' => 5],
            ['id' => 92, 'nombre' => 'Cacaopera', 'departamento_id' => 6],
            ['id' => 93, 'nombre' => 'Corinto', 'departamento_id' => 6],
            ['id' => 94, 'nombre' => 'El Rosario', 'departamento_id' => 6],
            ['id' => 95, 'nombre' => 'Joateca', 'departamento_id' => 6],
            ['id' => 96, 'nombre' => 'Jocoaitique', 'departamento_id' => 6],
            ['id' => 97, 'nombre' => 'Meanguera', 'departamento_id' => 6],
            ['id' => 98, 'nombre' => 'Perquín', 'departamento_id' => 6],
            ['id' => 99, 'nombre' => 'San Fernando', 'departamento_id' => 6],
            ['id' => 100, 'nombre' => 'San Isidro', 'departamento_id' => 6],
            ['id' => 101, 'nombre' => 'Torola', 'departamento_id' => 6],
            ['id' => 102, 'nombre' => 'Delicias de Concepción', 'departamento_id' => 6],
            ['id' => 103, 'nombre' => 'El Divisadero', 'departamento_id' => 6],
            ['id' => 104, 'nombre' => 'Gualococti', 'departamento_id' => 6],
            ['id' => 105, 'nombre' => 'Guatajiagua', 'departamento_id' => 6],
            ['id' => 106, 'nombre' => 'Jocoro', 'departamento_id' => 6],
            ['id' => 107, 'nombre' => 'Lolotiquillo', 'departamento_id' => 6],
            ['id' => 108, 'nombre' => 'Osicala', 'departamento_id' => 6],
            ['id' => 109, 'nombre' => 'San Carlos', 'departamento_id' => 6],
            ['id' => 110, 'nombre' => 'San Francisco Gotera', 'departamento_id' => 6],
            ['id' => 111, 'nombre' => 'San Simón', 'departamento_id' => 6],
            ['id' => 112, 'nombre' => 'Sensembra', 'departamento_id' => 6],
            ['id' => 113, 'nombre' => 'Sociedad', 'departamento_id' => 6],
            ['id' => 114, 'nombre' => 'Yamabal', 'departamento_id' => 6],
            ['id' => 115, 'nombre' => 'Yoloaiquín', 'departamento_id' => 6],
            ['id' => 116, 'nombre' => 'Olocuilta', 'departamento_id' => 7],
            ['id' => 117, 'nombre' => 'San Juan Talpa', 'departamento_id' => 7],
            ['id' => 118, 'nombre' => 'Cuyultitán', 'departamento_id' => 7],
            ['id' => 119, 'nombre' => 'San Luis Talpa', 'departamento_id' => 7],
            ['id' => 120, 'nombre' => 'San Francisco Chinameca', 'departamento_id' => 7],
            ['id' => 121, 'nombre' => 'Tapalhuaca', 'departamento_id' => 7],
            ['id' => 122, 'nombre' => 'El Rosario', 'departamento_id' => 7],
            ['id' => 123, 'nombre' => 'San Pedro Masahuat', 'departamento_id' => 7],
            ['id' => 124, 'nombre' => 'San Miguel Tepezontes', 'departamento_id' => 7],
            ['id' => 125, 'nombre' => 'San Juan Tepezontes', 'departamento_id' => 7],
            ['id' => 126, 'nombre' => 'San Antonio Masahuat', 'departamento_id' => 7],
            ['id' => 127, 'nombre' => 'San Pedro Nonualco', 'departamento_id' => 7],
            ['id' => 128, 'nombre' => 'Santa María Ostuma', 'departamento_id' => 7],
            ['id' => 129, 'nombre' => 'San Emigdio', 'departamento_id' => 7],
            ['id' => 130, 'nombre' => 'Paraíso de Osorio', 'departamento_id' => 7],
            ['id' => 131, 'nombre' => 'Jerusalén', 'departamento_id' => 7],
            ['id' => 132, 'nombre' => 'Mercedes La Ceiba', 'departamento_id' => 7],
            ['id' => 133, 'nombre' => 'Zacatecoluca (Capital o Cabecera departamental)', 'departamento_id' => 7],
            ['id' => 149, 'nombre' => 'San Luis La Herradura', 'departamento_id' => 7],
            ['id' => 153, 'nombre' => 'Santiago Nonualco', 'departamento_id' => 7],
            ['id' => 154, 'nombre' => 'San Juan Nonualco', 'departamento_id' => 7],
            ['id' => 155, 'nombre' => 'San Rafael Obrajuelo', 'departamento_id' => 7],
            ['id' => 157, 'nombre' => 'Candelaria de la Frontera', 'departamento_id' => 8],
            ['id' => 158, 'nombre' => 'Chalchuapa', 'departamento_id' => 8],
            ['id' => 159, 'nombre' => 'Coatepeque', 'departamento_id' => 8],
            ['id' => 160, 'nombre' => 'El Congo', 'departamento_id' => 8],
            ['id' => 161, 'nombre' => 'El Porvenir', 'departamento_id' => 8],
            ['id' => 162, 'nombre' => 'Masahuat', 'departamento_id' => 8],
            ['id' => 163, 'nombre' => 'Metapán', 'departamento_id' => 8],
            ['id' => 164, 'nombre' => 'San Antonio Pajonal', 'departamento_id' => 8],
            ['id' => 165, 'nombre' => 'San Sebastián Salitrillo', 'departamento_id' => 8],
            ['id' => 166, 'nombre' => 'Santa Ana', 'departamento_id' => 8],
            ['id' => 167, 'nombre' => 'Santa Rosa Guachipilín', 'departamento_id' => 8],
            ['id' => 168, 'nombre' => 'Santiago de la Frontera', 'departamento_id' => 8],
            ['id' => 169, 'nombre' => 'Texistepeque', 'departamento_id' => 8],
            ['id' => 170, 'nombre' => 'Comacarán', 'departamento_id' => 9],
            ['id' => 171, 'nombre' => 'Moncagua', 'departamento_id' => 9],
            ['id' => 172, 'nombre' => 'Quelepa', 'departamento_id' => 9],
            ['id' => 173, 'nombre' => 'San Miguel', 'departamento_id' => 9],
            ['id' => 174, 'nombre' => 'Uluazapa', 'departamento_id' => 9],
            ['id' => 175, 'nombre' => 'Chirilagua', 'departamento_id' => 9],
            ['id' => 176, 'nombre' => 'Carolina', 'departamento_id' => 9],
            ['id' => 177, 'nombre' => 'Chapeltique', 'departamento_id' => 9],
            ['id' => 178, 'nombre' => 'Ciudad Barrios', 'departamento_id' => 9],
            ['id' => 179, 'nombre' => 'Nuevo Edén de San Juan', 'departamento_id' => 9],
            ['id' => 180, 'nombre' => 'San Gerardo', 'departamento_id' => 9],
            ['id' => 181, 'nombre' => 'San Luis de la Reina', 'departamento_id' => 9],
            ['id' => 182, 'nombre' => 'Sesori', 'departamento_id' => 9],
            ['id' => 183, 'nombre' => 'San Antonio', 'departamento_id' => 9],
            ['id' => 184, 'nombre' => 'Chinameca', 'departamento_id' => 9],
            ['id' => 185, 'nombre' => 'El Tránsito', 'departamento_id' => 9],
            ['id' => 186, 'nombre' => 'Lolotique', 'departamento_id' => 9],
            ['id' => 187, 'nombre' => 'Nueva Guadalupe', 'departamento_id' => 9],
            ['id' => 188, 'nombre' => 'San Jorge', 'departamento_id' => 9],
            ['id' => 189, 'nombre' => 'San Rafael Oriente', 'departamento_id' => 9],
            ['id' => 190, 'nombre' => 'Aguilares', 'departamento_id' => 10],
            ['id' => 191, 'nombre' => 'El Paisnal', 'departamento_id' => 10],
            ['id' => 192, 'nombre' => 'Guazapa', 'departamento_id' => 10],
            ['id' => 193, 'nombre' => 'Apopa', 'departamento_id' => 10],
            ['id' => 194, 'nombre' => 'Nejapa', 'departamento_id' => 10],
            ['id' => 195, 'nombre' => 'Ilopango', 'departamento_id' => 10],
            ['id' => 196, 'nombre' => 'San Martín', 'departamento_id' => 10],
            ['id' => 197, 'nombre' => 'Soyapango', 'departamento_id' => 10],
            ['id' => 198, 'nombre' => 'Tonacatepeque', 'departamento_id' => 10],
            ['id' => 199, 'nombre' => 'Ayutuxtepeque', 'departamento_id' => 10],
            ['id' => 200, 'nombre' => 'Mejicanos', 'departamento_id' => 10],
            ['id' => 201, 'nombre' => 'Cuscatancingo', 'departamento_id' => 10],
            ['id' => 202, 'nombre' => 'Ciudad Delgado', 'departamento_id' => 10],
            ['id' => 203, 'nombre' => 'San Salvador', 'departamento_id' => 10],
            ['id' => 204, 'nombre' => 'San Marcos', 'departamento_id' => 10],
            ['id' => 205, 'nombre' => 'Santo Tomás', 'departamento_id' => 10],
            ['id' => 206, 'nombre' => 'Santiago Texacuangos', 'departamento_id' => 10],
            ['id' => 207, 'nombre' => 'Panchimalco', 'departamento_id' => 10],
            ['id' => 208, 'nombre' => 'Rosario de Mora', 'departamento_id' => 10],
            ['id' => 209, 'nombre' => 'Apastepeque', 'departamento_id' => 11],
            ['id' => 210, 'nombre' => 'Santa Clara', 'departamento_id' => 11],
            ['id' => 211, 'nombre' => 'Santo Domingo', 'departamento_id' => 11],
            ['id' => 212, 'nombre' => 'San Esteban Catarina', 'departamento_id' => 11],
            ['id' => 213, 'nombre' => 'San Ildefonso', 'departamento_id' => 11],
            ['id' => 214, 'nombre' => 'San Lorenzo', 'departamento_id' => 11],
            ['id' => 215, 'nombre' => 'San Sebastián', 'departamento_id' => 11],
            ['id' => 216, 'nombre' => 'Guadalupe', 'departamento_id' => 11],
            ['id' => 217, 'nombre' => 'San Cayetano Istepeque', 'departamento_id' => 11],
            ['id' => 218, 'nombre' => 'San Vicente', 'departamento_id' => 11],
            ['id' => 219, 'nombre' => 'Tecoluca', 'departamento_id' => 11],
            ['id' => 220, 'nombre' => 'Tepetitán', 'departamento_id' => 11],
            ['id' => 221, 'nombre' => 'Verapaz', 'departamento_id' => 11],
            ['id' => 222, 'nombre' => 'Acajutla', 'departamento_id' => 12],
            ['id' => 223, 'nombre' => 'Santa Catarina Masahuat', 'departamento_id' => 12],
            ['id' => 224, 'nombre' => 'Juayúa', 'departamento_id' => 12],
            ['id' => 225, 'nombre' => 'Nahuizalco', 'departamento_id' => 12],
            ['id' => 226, 'nombre' => 'Salcoatitán', 'departamento_id' => 12],
            ['id' => 227, 'nombre' => 'Izalco', 'departamento_id' => 12],
            ['id' => 228, 'nombre' => 'Armenia', 'departamento_id' => 12],
            ['id' => 229, 'nombre' => 'San Julián', 'departamento_id' => 12],
            ['id' => 230, 'nombre' => 'Santa Isabel Ishuatán', 'departamento_id' => 12],
            ['id' => 231, 'nombre' => 'Caluco', 'departamento_id' => 12],
            ['id' => 232, 'nombre' => 'Cuisnahuat', 'departamento_id' => 12],
            ['id' => 233, 'nombre' => 'San Antonio del Monte', 'departamento_id' => 12],
            ['id' => 234, 'nombre' => 'Santo Domingo de Guzmán', 'departamento_id' => 12],
            ['id' => 235, 'nombre' => 'Sonsonate', 'departamento_id' => 12],
            ['id' => 236, 'nombre' => 'Sonzacate', 'departamento_id' => 12],
            ['id' => 237, 'nombre' => 'Nahulingo', 'departamento_id' => 12],
            ['id' => 238, 'nombre' => 'La Unión (ciudad cabecera)', 'departamento_id' => 13],
            ['id' => 239, 'nombre' => 'San Alejo ', 'departamento_id' => 13],
            ['id' => 240, 'nombre' => 'Yucuaiquín ', 'departamento_id' => 13],
            ['id' => 241, 'nombre' => 'Conchagua ', 'departamento_id' => 13],
            ['id' => 242, 'nombre' => 'Intipucá ', 'departamento_id' => 13],
            ['id' => 243, 'nombre' => 'San José ', 'departamento_id' => 13],
            ['id' => 244, 'nombre' => 'El Carmen ', 'departamento_id' => 13],
            ['id' => 245, 'nombre' => 'Yayantique ', 'departamento_id' => 13],
            ['id' => 246, 'nombre' => 'Bolívar ', 'departamento_id' => 13],
            ['id' => 247, 'nombre' => 'Meanguera del Golfo ', 'departamento_id' => 13],
            ['id' => 248, 'nombre' => 'Santa Rosa de Lima ', 'departamento_id' => 13],
            ['id' => 249, 'nombre' => 'Pasaquina ', 'departamento_id' => 13],
            ['id' => 250, 'nombre' => 'Anamorós ', 'departamento_id' => 13],
            ['id' => 251, 'nombre' => 'Nueva Esparta ', 'departamento_id' => 13],
            ['id' => 252, 'nombre' => 'El Sauce ', 'departamento_id' => 13],
            ['id' => 253, 'nombre' => 'Concepción de Oriente ', 'departamento_id' => 13],
            ['id' => 254, 'nombre' => 'Polorós ', 'departamento_id' => 13],
            ['id' => 255, 'nombre' => 'Lislique ', 'departamento_id' => 13],
            ['id' => 256, 'nombre' => 'Alegría', 'departamento_id' => 14],
            ['id' => 257, 'nombre' => 'Berlín', 'departamento_id' => 14],
            ['id' => 258, 'nombre' => 'El Triunfo', 'departamento_id' => 14],
            ['id' => 259, 'nombre' => 'Estanzuelas', 'departamento_id' => 14],
            ['id' => 260, 'nombre' => 'Jucuapa', 'departamento_id' => 14],
            ['id' => 261, 'nombre' => 'Mercedes Umaña', 'departamento_id' => 14],
            ['id' => 262, 'nombre' => 'Nueva Granada', 'departamento_id' => 14],
            ['id' => 263, 'nombre' => 'San Buenaventura', 'departamento_id' => 14],
            ['id' => 264, 'nombre' => 'Santiago de María', 'departamento_id' => 14],
            ['id' => 265, 'nombre' => 'California', 'departamento_id' => 14],
            ['id' => 266, 'nombre' => 'Concepción Batres', 'departamento_id' => 14],
            ['id' => 267, 'nombre' => 'Ereguayquín', 'departamento_id' => 14],
            ['id' => 268, 'nombre' => 'Jucuarán', 'departamento_id' => 14],
            ['id' => 269, 'nombre' => 'Ozatlán', 'departamento_id' => 14],
            ['id' => 270, 'nombre' => 'Santa Elena', 'departamento_id' => 14],
            ['id' => 271, 'nombre' => 'San Dionisio', 'departamento_id' => 14],
            ['id' => 272, 'nombre' => 'Santa María', 'departamento_id' => 14],
            ['id' => 273, 'nombre' => 'Tecapán', 'departamento_id' => 14],
            ['id' => 274, 'nombre' => 'Usulután', 'departamento_id' => 14],
            ['id' => 275, 'nombre' => 'Jiquilisco', 'departamento_id' => 14],
            ['id' => 276, 'nombre' => 'Puerto El Triunfo', 'departamento_id' => 14],
            ['id' => 277, 'nombre' => 'San Agustín', 'departamento_id' => 14],
            ['id' => 278, 'nombre' => 'San Francisco Javier', 'departamento_id' => 14],
            ['id' => 279, 'nombre' => 'Arambala', 'departamento_id' => 6],
            ['id' => 280, 'nombre' => 'Chilanga', 'departamento_id' => 6],
        ];

        $this->db->table('municipios')->insertBatch($data);
    }
}
